#ifndef SUGI_CONFIG
#define SUGI_CONFIG

enum config {
    SUGI_CONF_GL_MAJOR_VERSION = 3,
    SUGI_CONF_GL_MINOR_VERSION = 3,
    SUGI_CONF_GL_DOUBLEBUFFER = 1,
    SUGI_CONF_GL_VSYNC = 1,
    SUGI_CONF_WINDOW_WIDTH = 512,
    SUGI_CONF_WINDOW_HEIGHT = 512,
};

#endif
